services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: ${DB_NAME:-road_slopes}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-road_slopes}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    command: streamlit run web-app/streamlit_app.py --server.address 0.0.0.0 --server.port 8501

volumes:
  postgres_data: 